class Block:
  def __init__(self,parameter):
    self.blockscore = parameter["blockscore"]
    self.extra_data = parameter["extraData"]
    self.gas_used = parameter["gasUsed"]
    self.governance_data = parameter["governanceData"]
    self.hash = parameter["hash"]
    self.number = parameter["number"]
    self.parent_hash = parameter["parentHash"]
    self.logs_bloom = parameter['logsBloom']
    self.transactions_root = parameter['transactionsRoot']
    self.state_root = parameter['stateRoot']
    self.receipts_root = parameter['receiptsRoot']
    self.reward = parameter['reward']
    self.block_score = parameter['blockScore']
    self.total_block_score = parameter['totalBlockScore']
    self.size = parameter['size']
    self.timestamp = parameter['timestamp']
    self.timestamp_FoS = parameter['timestampFoS']
    self.transactions = parameter['transactions']
    self.vote_data = parameter['voteData']